nameOverride: "devspaces"
fullnameOverride: ""

namespace: ""

devEnvironments:
  startTimeoutSeconds: 300
  secondsOfRunBeforeIdling: -1
  secondsOfInactivityBeforeIdling: -1
  maxNumberOfWorkspacesPerUser: 2
  defaultEditor: che-incubator/che-code/latest
  resources:
    limits:
      memory: 6Gi
      cpu: "4"
    requests:
      memory: 512Mi
      cpu: 500m

gitlab:
  host: ""

argocd:
  enabled: true
  instance:
    syncwave: "0"
