nameOverride: streams-console

namespace:
subdomain:

kafka:
  name: kafka
  authentication:
    saslMechanism: SCRAM-SHA-512
  authorization: simple

argocd:
  syncwave:
    enabled: true
    console: "1"
