nameOverride: ""

serviceMesh:
  channel: stable-3.2
  installPlanApproval: Automatic
  name: servicemeshoperator3
  source: redhat-operators
  sourceNamespace: openshift-marketplace

kiali:
  channel: stable
  installPlanApproval: Automatic
  name: kiali-ossm
  source: redhat-operators
  sourceNamespace: openshift-marketplace

istio:
  namespace: istio-system
  discoverySelector:
    matchLabels:
      istio-discovery: enabled

istioCni:
  namespace: istio-cni
