nameOverride: "developer-hub-prereqs"

namespace: rhdh

vault:
  namespace: vault
  name: vault

operator:
  channel: fast-1.8
  startingCSV: rhdh-operator.v1.8.3

argocd:
  enabled: true
  syncwave: "-1"
